### ISSUE TITLE
undefined reference to `eglDestroyImageKHR'

### ISSUE THREAD

**Issue by EoD** [axeldavy/Xnine#2]
When I am trying to build Xnine without any changes to the Makefile, I get complaints about some missing files:

```
$ make
gcc -c Xnine.c -o Xnine.o -I include/D3D9 -I include -DD3DADAPTERPATH='"/usr/lib/x86_64-linux-gnu/d3d/d3dadapter9.so"' -DD3DADAPTER9_WITHDRI2=1
gcc -c -g dri3.c -o dri3.o -I include/D3D9 -DD3DADAPTER9_WITHDRI2=1
gcc triangle.c Xnine.o dri3.o -ldl -lEGL -lGL -lX11 -lXext -lxcb -lxcb-present -lxcb-dri3 -lxcb-xfixes -lX11-xcb -I include/D3D9 -o triangle_c
dri3.o: In function `DRI2FallbackPRESENTPixmap':
/tmp/Xnine/dri3.c:991: undefined reference to `eglDestroyImageKHR'
/tmp/Xnine/dri3.c:1017: undefined reference to `eglDestroyImageKHR'
collect2: error: ld returned 1 exit status
Makefile:20: recipe for target 'triangle_c' failed
make: *** [triangle_c] Error 1
```

When I am building with `DD3DADAPTER9_WITHDRI2=0`, the compile finishes without errors.

**Comment by axeldavy** [comment]
Apparently we didn't update the dri2 backend for the Mesa egl changes.

Mesa stopped advertising eglDestroyImageKHR and others. The wine backend was updated, but not Xnine.
I'll add that to my TODO list.

**Comment by EoD** [comment]
FTR: <sarnex> basically you need to port this commit to xnine https://github.com/iXit/wine/commit/fe65b13997633678a8db40fece12bb62b3a3cca2
