### ISSUE TITLE
Background of triangle_SDL is flickering blue/black

### ISSUE THREAD

**Issue by EoD** [axeldavy/Xnine#3]
When I build Xnine with `D3DADAPTER9_WITHDRI2=0` the executable `triangle_SDL` has massive black/blue flickering in its background. The triangle itself looks fine.

`triangle_c` and `triangle_cpp` look fine.

**Comment by axeldavy** [comment]
That could be a bug in Nine we solved recently. Are you using Mesa ixit git ?

**Comment by EoD** [comment]
I am testing it with mesa git + ixit patches by NPHardass: https://github.com/NP-Hardass/mesa-d3d9-patches/blob/5951ae15cc5f58d6b78b6aa103631c6c8f9c6bcd/mesa-d3d9.patch

**Comment by EoD** [comment]
Apparently this is related to the `col++` in https://github.com/axeldavy/Xnine/blob/master/triangle_SDL.cpp#L34 
and using `D3DPRESENT_INTERVAL_IMMEDIATE` in https://github.com/axeldavy/Xnine/blob/master/triangle_SDL.cpp#L110 .

So either removing the "black-> blue fading" feature (done by `col++`) or restricting the FPS to the refresh rate (by using `D3DPRESENT_INTERVAL_DEFAULT`).
